# Generated by Django 4.0.4 on 2022-05-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('heroes_villains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_villain',
            name='super_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_types.super_type'),
        ),
    ]
